name: Build Better Hosting Solution (base)
description: Builds the solution

inputs:
  Configuration:
    description: Debug/Release build configuration
    required: true
    #type: string
    default: 'Release'
  NightlyID:
    description: the Nightly msbuild value, empty, null, or the string '0' for not nightly
    required: false
    #type: number
    default: ''
  IsNightly:
    description: the Nightly msbuild value, empty, null, or the string '0' for not nightly
    required: false
    #type: boolean
    default: ''

runs:
  using: "composite"
  steps:
    - name: Restore dependencies
      shell: bash
      run: dotnet restore --verbosity minimal

    - name: Build
      shell: bash
      run: |
        if [[ ${{ inputs.IsNightly }} == true ]]; then
            dotnet build BetterHosting.sln --no-restore --configuration ${{ inputs.Configuration }} -p:Nightly=${{ inputs.NightlyID }}
        else
            dotnet build BetterHosting.sln --no-restore --configuration ${{ inputs.Configuration }}
        fi
        