name: Test Better Hosting Library

inputs:
  Configuration:
    required: true
    type: string
    default: Release
  SolutionAlreadyBuilt:
    required: true
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
  - uses: ./.github/workflows/action_buildSolution.yml
    with:
    Configuration: ${{ inputs.Configuration }}
    if: ${{ inputs.SolutionAlreadyBuilt == true }}

  - name: Test
    run: dotnet test --no-restore --configuration ${{ inputs.configuration }} --no-build --verbosity normal -l trx 