name: Test Better Hosting Library
description: Tests the solution

inputs:
  Configuration:
    description: Debug/Release build configuration
    required: true
    #type: string
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Run dotnet test
      shell: bash
      run: dotnet test BetterHosting.sln --verbosity normal --configuration ${{ inputs.Configuration }}
      #--no-restore --no-build