name: Test Better Hosting Library
description: Tests the solution

inputs:
  Configuration:
    description: Debug/Release build configuration
    required: true
    #type: string
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Run dotnet test
      shell: bash
      run: dotnet test BetterHosting.sln --settings:"./UnitTests/.runsettings" --results-directory:"./UnitTests/TestResults"
      # --no-restore --no-build
    - name: Upload test results
      if: ${{ always() }} # Always publish results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: ./UnitTests/TestResults/*.trx
           
    - name: Upload code coverage
      if: ${{ always() }} # Always publish results
      uses: actions/upload-artifact@v3
      with:
         name: dotnet-coverage
         path: ./UnitTests/TestResults/**/coverage.cobertura.xml

    - name: Generate (nice) report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: './UnitTests/TestResults/**/coverage.cobertura.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'HtmlInline;Html_Dark;Cobertura' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, OpenCover, CsvSummary, Html, Html_Dark, Html_Light, Html_BlueRed, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlInline_AzurePipelines_Light, HtmlSummary, Html_BlueRed_Summary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MarkdownSummaryGithub, MarkdownDeltaSummary, MHtml, SvgChart, SonarQube, TeamCitySummary, TextSummary, TextDeltaSummary, Xml, XmlSummary
        historydir: '' # Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.
        plugins: '' # Optional plugin files for custom reports or custom history storage (separated by semicolon).
        assemblyfilters: '+*' # Optional list of assemblies that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        classfilters: '+*' # Optional list of classes that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        filefilters: '+*' # Optional list of files that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
        verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
        title: '' # Optional title.
        tag: '${{ github.run_number }}_${{ github.run_id }}' # Optional tag or build version.
        customSettings: '' # Optional custom settings (separated by semicolon). See: https://github.com/danielpalme/ReportGenerator/wiki/Settings.
        toolpath: 'reportgeneratortool' # Default directory for installing the dotnet tool.

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport # Artifact name        
        path: coveragereport # Directory containing files to upload
