name: Test Better Hosting Library
description: Tests the solution

inputs:
  Configuration:
    description: Debug/Release build configuration
    required: true
    #type: string
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Run dotnet test
      shell: bash
      run: dotnet test BetterHosting.sln --logger trx
      # --verbosity normal --configuration ${{ inputs.Configuration }}
      #run: dotnet test --logger trx --results-directory "TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: ./TestResults/**
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.3.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./TestResults/**/*.trx
        coverage-path: ./TestResults/**/coverage.cobertura.xml
        coverage-threshold: 75
      if: ${{ always() }}
            