name: Test Better Hosting Library

on:
  workflow_call:
    inputs:
      Configuration:
        required: true
        type: string
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./action_buildSolution.yml
      with:
        Configuration: ${{ inputs.Configuration }}
    - name: Test
      run: dotnet test --no-restore --configuration ${{ inputs.configuration }} --no-build --verbosity normal -l trx 