name: Build Better Hosting Solution (base)

on:
  workflow_call:
    inputs:
      Configuration:
        required: true
        type: string
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./action_buildSolution.yml
      with:
        Configuration: ${{ inputs.Configuration }}
    - name: Publish
      run: dotnet publish --configuration  ${{ inputs.Configuration }}