name: Run Testing

on:
  push:
    branches:
    - master
    - develop
    - 'feature/**'
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/startup
    #- uses: ./.github/actions/setupDotNet
    #
    #- uses: ./.github/actions/buildSolution
    #  with:
    #    Configuration: 'Release'
    #- name: Build solution
    #  run: dotnet build --no-restore --configuration Release
    #- uses: ./.github/actions/runTests
    #  with:
    #    Configuration: 'Release'
    #- name: Test
    #  run: dotnet test --no-restore --no-build --verbosity normal