name: Run Testing

on:
  push:
    branches:
    - master
    - develop
    - 'feature/**'
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Install .NET
      uses: ./.github/actions/setupDotNet
    - name: Run Unit Tests
      uses: ./.github/actions/runTests

    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.3.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./TestResults/**/*.trx
        coverage-path: ./TestResults/**/coverage.cobertura.xml
        coverage-threshold: 75
      if: ${{ always() }}
 