name: Run Testing

on:
  push:
    branches:
    - master
    - develop
    - 'feature/**'
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Install .NET
      uses: ./.github/actions/setupDotNet
    - name: Run Unit Tests
      uses: ./.github/actions/runTests
  
    #below is temp for testing
 #   - name: Test
 #     run: dotnet test BetterHosting.sln --no-restore --no-build --verbosity normal --configuration 'Release'

    #
    #- uses: ./.github/actions/buildSolution
    #  with:
    #    Configuration: 'Release'
    #- name: Build solution
    #  run: dotnet build --no-restore --configuration Release
    #- uses: ./.github/actions/runTests
    #  with:
    #    Configuration: 'Release'
    #- name: Test
    #  run: dotnet test --no-restore --no-build --verbosity normal