name: Run Testing

on:
  push:
    branches:
    - master
    - develop
    - 'feature/**'
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/action_runTests.yml
      with:
        Configuration: ${{ inputs.Configuration }}