name: Run Testing

on:
  push:
    branches:
    - master
    - develop
    - 'feature/**'
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
#   - uses: ./.github/actions/runTests
#     with:
#       Configuration: 'Release'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal --logger "console;trx;verbosity=normal"